object Versions {
    const val kotlin = "1.9.10"
    const val coroutines = "1.7.3"
    const val appCompat = "1.6.1"
    const val material = "1.9.0"
    const val material3 = "1.2.0-rc01" // Material3
    const val constraintLayout = "2.1.4"
    const val mockk = "1.13.5"
    const val junit = "4.13.2"
    const val retrofit = "2.9.0"
    const val retrofitCoroutines = "0.9.2"
    const val okhttp = "4.9.3"
    const val androidxTestExtJunit = "1.1.5"
    const val lifecycle = "2.8.0"
    const val compose = "1.5.1"
    const val composeUi = "1.5.1"
    const val composeMaterial = "1.5.1"
    const val composeUiTooling = "1.5.1"
    const val koin = "4.0.0-RC1"
    const val koinAndroid = "4.0.0-RC1"
    const val koinAndroidCompose = "4.0.0-RC1"
    const val gson = "2.10.1"
    const val navVersion = "2.7.1"
    const val core = "1.12.0"
    const val timber = "5.0.1"
    const val coil = "2.4.0"
}

object Deps {
    const val kotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val junit = "junit:junit:${Versions.junit}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitConverterGson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val retrofitCoroutines =
        "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:${Versions.retrofitCoroutines}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val androidxTestExtJunit = "androidx.test.ext:junit:${Versions.androidxTestExtJunit}"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val composeRuntime = "androidx.compose.runtime:runtime:${Versions.compose}"
    const val composeUi = "androidx.compose.ui:ui:${Versions.composeUi}"
    const val composeMaterial = "androidx.compose.material:material:${Versions.composeMaterial}"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling:${Versions.composeUiTooling}"
    const val material3 = "androidx.compose.material3:material3:${Versions.material3}"
    const val koinCore = "io.insert-koin:koin-core:${Versions.koin}"
    const val koinBom = "io.insert-koin:koin-bom:${Versions.koin}"
    const val koinCoroutine = "io.insert-koin:koin-core-coroutines:${Versions.koin}"
    const val koinAndroid = "io.insert-koin:koin-android:${Versions.koinAndroid}"
    const val koinAndroidCompose = "io.insert-koin:koin-androidx-compose:${Versions.koinAndroidCompose}"
    const val koinAndroidComposeNavigation = "io.insert-koin:koin-androidx-compose-navigation:${Versions.koinAndroidCompose}"
    const val koinCompose = "io.insert-koin:koin-compose:${Versions.koinAndroidCompose}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val navFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navVersion}" // Navigation Fragment
    const val navUi = "androidx.navigation:navigation-ui-ktx:${Versions.navVersion}" // Navigation UI
    const val core = "androidx.core:core-ktx:${Versions.core}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val coil = "io.coil-kt:coil-compose:${Versions.coil}"
}